
server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"


# 数据库连接配置
database:
  logger:
    path:    "logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]

  default:
    #todo
    link:   "mysql:root:Zsm@20020609@tcp(127.0.0.1:3306)/shop"
    debug:  true

redis:
  default:
    address: 127.0.0.1:6379
    db: 1
    pass: zsm20020609
    idleTimeout: 600
