// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "shop-v2/internal/logic/admin"
	_ "shop-v2/internal/logic/position"
	_ "shop-v2/internal/logic/rotation"
)
